name: Mirror to GitLab

on: [push, workflow_dispatch]

jobs:
  mirror_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Mirror Repository to GitLab
        uses: cssnr/mirror-repository-action@v1
        with:
          # Use your GitLab URL here (keep the .git at the end)
          url: https://gitlab.com/Brian-Gabrielson/homelab-draft.git
          username: Brian-Gabrielson
          password: ${{ secrets.GITLAB_TOKEN }}
